trigger:
- master

pool: 
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Maven Build docker build'
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package -DskipTests'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - script: |
        docker build -t mvn-spring:$(Build.SourceVersion) . -f Dockerfile-v2
        docker tag mvn-spring:$(Build.SourceVersion) mvnrepo.azurecr.io/mvn-spring:testv1
        az acr login -n mvnrepo.azurecr.io --username mvnrepo --password wFzE/+c2VTXgp4bCqZjrBEfJ8bXC/LHNvxGb0z/5+1+ACRDP4yVJ
        docker push mvnrepo.azurecr.io/mvn-spring:testv1

