name: Second-pipeline

trigger:
- none

resources:
  pipelines:
  - pipeline: Secondpipeline
    source: imagebuildandpush
    trigger: 
     branches:
     - master

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPushJob
    displayName: 'Build and Push Image'
    steps:
    - script: |
        #!/bin/bash
        today=$(date '+%Y%m%d%H%M%S')
        echo "##vso[task.setvariable variable=imageTag]$today"
      displayName: 'Set Image Tag'

- stage: Deploy
  jobs:
  - job: DeployJob
    displayName: 'Deploy to Kubernetes'
    steps:
    - task: replacetokens@5
      inputs:
        rootDirectory: 'Deployment_files'
        targetFiles: '**/deployment.yaml'
        encoding: 'auto'
        tokenPattern: 'default'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true

    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'Saitejak8serviceconnection'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'Deployment_files/deployment.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        azureSubscriptionEndpointForSecrets: 'Free Trial(7338b8ab-3b46-420e-becc-da044eebe12c)'
        azureContainerRegistry: 'saitejacontainerregistry.azurecr.io'
        secretName: 'saitejak8secret4'