# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Second-pipeline

trigger:
- none
resources:
  pipelines:
  - pipeline: firstpipeline # Name of the pipeline resource.
    source: First-pipeline # The name of the pipeline referenced by this pipeline resource.
    trigger: 
      branches:
      - master

pool:
  vmImage: ubuntu-latest

jobs:
- job: Deploy
  displayName: Deploy to Kubernetes
  steps:
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'k8s-serviceconnection'
      namespace: 'default'
      command: 'apply'
      imagePullPolicy: Always
      useConfigurationFile: true
      configuration: 'Deployment_files/deployment.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'
      azureSubscriptionEndpointForSecrets: 'Free Trial(7338b8ab-3b46-420e-becc-da044eebe12c)'
      azureContainerRegistry: 'saitejacontainerregistry.azurecr.io'
      secretName: 'container-registry-secret'
      containers: |
        $(azureContainerRegistry)/saitejaproject:latest
