# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Second-pipeline

trigger:
- none
resources:
  pipelines:
  - pipeline: secondpipeline # Name of the pipeline resource.
    source: imagebuildandpush # The name of the pipeline referenced by this pipeline resource.
    trigger: 
     branches:
     - master

pool:
  vmImage: ubuntu-latest

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s-serviceconnection'
    namespace: 'default'
    command: 'apply'
    imagePullPolicy: Always
    useConfigurationFile: true
    configuration: 'Deployment_files/deployment.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Free Trial(7338b8ab-3b46-420e-becc-da044eebe12c)'
    azureContainerRegistry: 'saitejacontainerregistry.azurecr.io'
    secretName: 'container-registry-secret'
    containers: |
            $(saitejacontainerregistry.azurecr.io):$(buildid)