# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Second-pipeline
trigger:
- none
resources:
  pipelines:
  - pipeline: Secondpipeline # Name of the pipeline resource.
    source: imagebuildandpush # The name of the pipeline referenced by this pipeline resource.
    trigger: 
     branches:
     - master

pool:
  vmImage: ubuntu-latest

variables:
  Image_tag: '$(Build.BuildId)'

steps:

- task: Bash@3
  displayName: 'Set Image Tag and Deploy'
  inputs:
    targetType: 'inline'
    script: |
      # Set the imageTag to today's date
      imageTag=$(date +"%Y%m%d")


- task: replacetokens@5
  inputs:
    rootDirectory: 'Deployment_files'
    targetFiles: '**/deployment.yaml'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'Saitejak8serviceconnection'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'Deployment_files/deployment.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Free Trial(7338b8ab-3b46-420e-becc-da044eebe12c)'
    azureContainerRegistry: 'saitejacontainerregistry.azurecr.io'
    secretName: 'saitejak8secret'
