---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb1
  template:
    metadata:
      labels:
        app: mongodb1
    spec:
      containers:
      - name: mongodb1
        image: docker.io/library/mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service1
spec:
  selector:
    app: mongodb1
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017