trigger:
- skmdm

#pool: myagentpool
#  vmImage: 'ubuntu-latest'

variables:
  # Define date and time variables
  currentDate: $(date +%Y%m%d)
  currentTime: $(date +%H%M%S)

stages:
- stage: sonar
  displayName: 'sonar code analysis'
  jobs:
  - job: sonarJob
    pool: sonar-selfhost-agent
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'sonar-mvn-conection'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'mvn-code-analysis'
        cliProjectName: 'mvn-spring'
        cliSources: '.'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.java.binaries=.
    - task: SonarQubeAnalyze@5
      inputs:
        jdkversion: 'JAVA_HOME_11_X64'
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'


- stage: Build
  displayName: 'Maven Build docker build'
  jobs:
  - job: BuildJob
    pool: myagentpool
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package -DskipTests'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - script: |
        imageTag=$(currentDate)-$(currentTime)
        docker build -t mvn-spring:$imageTag .
        docker tag mvn-spring:$imageTag mvnrepo.azurecr.io/mvn-spring:$imageTag
        az acr login -n mvnrepo.azurecr.io --username mvnrepo --password wFzE/+c2VTXgp4bCqZjrBEfJ8bXC/LHNvxGb0z/5+1+ACRDP4yVJ
        docker push mvnrepo.azurecr.io/mvn-spring:$imageTag
        echo $imageTag > $(Build.ArtifactStagingDirectory)/imageTag.txt

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'image-tag'
        publishLocation: 'Container'

        

        
